name: Send LINE Messages

on: 
  schedule:
    - cron: '0 0 * * *' # 毎日 00:00 UTC (日本時間 9:00)
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest

    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          export PYTHONPATH=src
          poetry install --no-root

      - name: Pull latest changes
        run: git pull

      - name: Run script
        env: 
          CHANNEL_ACCESS_TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          PLAYLIST_ID: ${{ secrets.PLAYLIST_ID }}
        run: |
          export PYTHONPATH=src
          poetry run python main.py

      - name: Commit updated sent_videos.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sent_videos.json
          git commit -m "Update sent videos [skip ci]" || echo "No changes to commit"
          git push
